---
# tasks file for clients
- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ helper.install_bin_dir }}"

- name: Download openshift-install archive {{ openshift_installer.archive_url }}
  ansible.builtin.get_url:
    url: "{{ openshift_installer.archive_url }}"
    dest: "{{ helper.install_bin_dir }}/{{ openshift_installer.archive_url | basename }}"
  retries: 3

- name: Extract openshift-install
  unarchive:
    remote_src: yes # target server에 압축파일이 존재하는 지 여부 설정
    src: "{{ helper.install_bin_dir }}/{{ openshift_installer.archive_url | basename }}"
    dest: "{{ helper.install_bin_dir }}"
    exclude:
      - README.md

- name: Download oc client archive {{ openshift_client.archive_url }}
  ansible.builtin.get_url:
    url: "{{ openshift_client.archive_url }}"
    dest: "{{ helper.install_bin_dir }}/{{ openshift_client.archive_url | basename }}"
  retries: 3

- name: Extract oc client
  unarchive:
    remote_src: yes
    src: "{{ helper.install_bin_dir }}/{{ openshift_client.archive_url | basename }}"
    dest: "{{ helper.install_bin_dir }}"
    exclude:
      - README.md

- name: Get installer info
  command: "{{ helper.install_exe }} version"
  changed_when: False
  register: installer_version

- name: Show installer info
  debug:
    var: installer_version.stdout_lines
