rpm_name_map:
  CentOS:
    default:
      python-jsonpatch: python-jsonpatch
      python-ovirt-engine-sdk4: python-ovirt-engine-sdk4
      python-dns: python-dns
      libvirt-python: libvirt-python
      python-pyghmi: python-pyghmi
      python-pyvmomi: python-pyvmomi
    '8':
      python-jsonpatch: python3-jsonpatch
      python-ovirt-engine-sdk4: python3-ovirt-engine-sdk4
      python-dns: python3-dns
      libvirt-python: libvirt-python3
      python-pyghmi: python3-pyghmi
      python-pyvmomi: python3-pyvmomi
  Fedora:
    default:
      python-jsonpatch: python3-jsonpatch
      python-ovirt-engine-sdk4: python3-ovirt-engine-sdk4
      python-dns: python3-dns
      libvirt-python: python3-libvirt
      python-pyghmi: python3-pyghmi
      python-pyvmomi: python3-pyvmomi

rpm_name: >
  {{ rpm_name_map[ansible_distribution][ansible_distribution_major_version]
  | default(rpm_name_map[ansible_distribution]['default']) }}
