- name: Ensure required directory exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ helper.timestamp_dir }}"

- name: Check if timestamp {{ helper.timestamp_ignition_created }} exists
  ansible.builtin.stat:
    path: "{{ helper.timestamp_ignition_created }}"
  register: timestamp_ignition_created

- name: Configure installer
  ansible.builtin.import_tasks: generate_ignition_tasks.yml
  when: not timestamp_ignition_created.stat.exists

- name: Create timestamp {{ helper.timestamp_ignition_created }}
  ansible.builtin.file:
    path: "{{ helper.timestamp_ignition_created }}"
    state: touch
    mode: "0755"
  when: not timestamp_ignition_created.stat.exists

- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ helper.install_ignition_dir }}"

- name: Install jsonpatch utility
  ansible.builtin.yum:
    name: '{{ rpm_name["python-jsonpatch"] }}'
    state: present
  become: true

- name: Create indivisual ignition files
  ansible.builtin.copy:
    src: "{{ helper.install_conf_dir }}/{{ item.ignition_config }}"
    dest: "{{ helper.install_ignition_dir }}/{{ item.hostname }}.ign"
    remote_src: true
    backup: true
    mode: "0755"
  with_items: "{{ openshift_cluster_hosts }}"

- name: Generate ignition transform script
  ansible.builtin.template:
    src: transform_ignition.sh
    dest: "{{ helper.install_ignition_dir }}"
    mode: "0755"

- name: Run ignition transform script
  ansible.builtin.command:
    cmd: "{{ helper.install_ignition_dir }}/transform_ignition.sh"
  changed_when: false
