dhcp_server:
  dhcp_range: 192.168.150.20,192.168.150.254,255.255.255.0
  # The set of option-names known by dnsmasq can be discovered by running "dnsmasq --help dhcp"
  dhcp_options:
    router: 192.168.150.1
    netmask: 255.255.255.0
    dns-server: 192.168.150.1
    # When using an overay network (vxlan, gre ) between the Openshift hosts,
    # you will need the mtu value: Default mtu is 1500.
    # mtu: 1450
