helper:
  # ansible_env 사용은 되도록이면 지양
  install_dir: '{{ ansible_env["HOME"] }}/openshift-workspace'
  install_bin_dir: '{{ ansible_env["HOME"] }}/openshift-workspace/{{ openshift_install_config.name}}/bin'
  oc_exe: '{{ ansible_env["HOME"] }}/openshift-workspace/{{ openshift_install_config.name}}/bin/oc'
  install_exe: '{{ ansible_env["HOME"] }}/openshift-workspace/{{ openshift_install_config.name}}/bin/openshift-install'
  install_conf_dir: '{{ ansible_env["HOME"] }}/openshift-workspace/{{ openshift_install_config.name}}/conf'
  install_ignition_dir: '{{ ansible_env["HOME"] }}/openshift-workspace/{{ openshift_install_config.name}}/ignition'
  images_dir: '{{ ansible_env["HOME"] }}/openshift-workspace/{{ openshift_install_config.name}}/images'
  mirror_registry_dir: '{{ ansible_env["HOME"] }}/openshift-workspace/{{ openshift_install_config.name}}/mirror_registry'
  timestamp_dir: '{{ ansible_env["HOME"] }}/openshift-workspace/{{ openshift_install_config.name}}/timestamps'
  timestamp_ignition_created: '{{ ansible_env["HOME"] }}/openshift-workspace/{{ openshift_install_config.name}}/timestamps/ignition_created'
  web_dir: '/var/www/html/openshift-auto-upi'
  web_cluster_dir: '/var/www/html/openshift-auto-upi/{{ openshift_install_config.name}}'
  tftp_dir: '/var/lib/tftpboot/openshift-auto-upi'
  tftp_cluster_dir: '/var/lib/tftpboot/openshift-auto-upi/{{ openshift_install_config.name }}'
