---
# tasks file for web_server
- name: Install Apache httpd web server
  yum:
    name: httpd
    state: present
  become: true

- name: Listen on port 81 to avoid conflict whth load balancer
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^Listen"
    line: Listen 81
  notify: Restart httpd
  become: true

- name: Enable httpd server on boot and start it
  service:
    name: httpd
    state: started
    enabled: yes
  become: true

- name: Is firewalld running?
  command: firewalld-cmd --state
  changed_when: False
  failed_when: False
  register: firewalld
  become: true

- name: Open port 81/tcp on firewall
  firewalld:
    port: 81/tcp
    permanent: yes
    immedidate: yes
    state: enabled
  when: firewalld.rc == 0
  become: true

- name: Create a web dir '{{ helper.web_cluster_dir }}'
  file:
    path: "{{ helper.web_cluster_dir }}"
    owner: "{{ ansible_real_user_id | int }}"
    group: "{{ ansible_real_group_id | int }}"
    state: directory
  become: true
