- name: Create bootstrap machine
  community.vmware.vmware_guest:
    hostname: "{{ vsphere.vcenter_hostname }}"
    username: "{{ vsphere.vcenter_username }}"
    password: "{{ vsphere.vcenter_password }}"
    validate_certs: "{{ vsphere.validate_certs }}"
    datacenter: "{{ vsphere. datacenter_name }}"
    folder: "/Datacenter/vm/mycluster"
    name: bootstrap
    guest_id: rhel8_64Guest
    networks:
      - name: "OCP Network"
        mac: 00:50:56:3c:0a:3d
        device_type: vmxnet3
    disk:
      - size_gb: "{{ item.disk_gb }}"
        type: thin
        datastore: "{{ vsphere.datastore_name }}"
    hardware:
      memory_mb: "{{ item.memory_gb * 1024 }}"
      num_cpus: "{{ item.num_cpus }}"
      scsi: paravirtual
      hotadd_cpu: false
      hotremove_cpu: false
      hotadd_memory: false
    state: present
  loop: "{{ openshift_cluster_hosts }}"

# - name: Attache virtual machine to network {{ vsphere.network_name }}
#   vmware_guest:
#     hostname: "{{ vsphere.vcenter_hostname }}"
#     username: "{{ vsphere.vcenter_username }}"
#     password: "{{ vsphere.vcenter_password }}"
#     datacenter: "{{ vsphere.datacenter_name }}"
#     name: bootstrap
#     networks:
#       - name: "{{ vsphere.network_name }}"
#         mac: "{{ item.macaddr }}"
#     validate_certs: "{{ vsphere.validate_certs }}"
#     state: present
#   loop: "{{ openshift_cluster_hosts }}"

- name: Power on virtual machine {{ virtual_machine_names[item.hostname] }}
  vmware_guest:
    hostname: "{{ vsphere.vcenter_hostname }}"
    username: "{{ vsphere.vcenter_username }}"
    password: "{{ vsphere.vcenter_password }}"
    name: "bootstrap"
    validate_certs: "{{ vsphere.validate_certs }}"
    state: poweredon
