---
# tasks file for openshift_baremetal
- name: Generate ignition configs
  ansible.builtin.import_role:
    name: openshift_common
    tasks_from: generate_ignition.yml

- name: Ensure prerequisites
  ansible.builtin.import_tasks: ensure_prereqs.yml

- name: Deploy hosts
  ansible.builtin.import_tasks: deploy_hosts.yml

- name: Wait for ssh on Openshift hosts
  ansible.builtin.import_role:
    name: openshift_common
    tasks_from: wait_for_ssh.yml
  vars:
    wait_for_ssh_existing_vms: "{{ vsphere_existing_vms }}"

- name: Wait for the bootstrap to complete
  ansible.builtin.import_role:
    name: openshift_common
    tasks_from: wait_for_bootstrap.yml

- name: Stop bootstrap virtual machine
  ansible.builtin.import_tasks: stop_bootstrap_vm.yml

- name: Wait for the installation to complete
  ansible.builtin.import_role:
    name: openshift_common
    tasks_from: wait_for_install.yml
